//LOCALHOST
### Get All Contacts
GET http://localhost:3000/contacts

### Get Contact By Id
GET http://localhost:3000/contacts/6736fc076103623ce575e132

### Add New Contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "_id": 1,
    "firstName": "Joel",
    "lastName": "Opute",
    "email": "joelcopute@gmail.com",
    "favoriteColor": "white",
    "birthdate": "03-12-1987"
}

### Update a Contact
PUT http://localhost:3000/contacts/67370d4ff1caf75950e9eb83 HTTP/1.1
content-type: application/json

{   
    "firstName": "Donald",
    "lastName": "Opute",
    "email": "donald.opute@gmail.com",
    "favoriteColor": "black",
    "birthdate": "12-02-1985"
}

### Delete a Contact
DELETE http://localhost:3000/contacts/673728f542933fea8bcda780 HTTP/1.1


// PRODUCTION
### Get All Contacts
GET https://cse341-87qw.onrender.com/contacts

### Get Contact By Id
GET https://cse341-87qw.onrender.com/contacts/6736fc076103623ce575e132


